### PR TITLE
Generate statistics page based on the corpusstats library.

### PR DESCRIPTION
**Pull request by yrammos**
Also format code according to the PEP style guide.

### CODE REVIEW

**Comment by yrammos** [comment]
The `corpusstats` Python library must be installed by the GitHub action for this PR to pass.

**Comment by johentsch** [comment]
Hey @yrammos , I couldn't test the script because I'm missing the corpusstats dependency and couldn't find its repo. Could you please make it available?

**Comment by yrammos** [comment]
Hi @johentsch,

It's https://github.com/DCMLab/corpus_statistics_generator.

The graphics are still rough and need a facelift.

**Comment by johentsch** [comment]
Ahh right, forgot. Thanks!

**Pull request merged**
